CFG_TEE_TA_LOG_LEVEL ?= 4
CFG_TA_OPTEE_CORE_API_COMPAT_1_1=y

BINARY=11223344-5566-7788-99aa-bbccddeeff00

-include /home/code/optee/optee_os/out/arm/export-ta_arm64/mk/ta_dev_kit.mk

addclean:
	@rm -f *.o *.cmd *.d *.map *.dmp *.stripped.elf *.elf *.ta *.ld.d